title="simulation"
[DDR]
DDR_CAPACITY = 6  # GB

[chip]
CORE_NUM = 30
MEMORY_CAPACITY = 30  # M
INT8_COMPUTATION = 44 # TOPS
FP16_COMPUTATION = 22 # TFLOPS
FP32_COMPUTATION = 0.1 # TFLOPS
SCHEDULE = "QUEUE"

[group-level-1]
CHIP_NUM = 1
DDR_NUM = 1
CHIP_DDR_BANDWIDTH = 12 # GB/s

[group-level-2]
GROUP1_BANDWIDTH = 2 # GB/s
CONNECTION = "x+1|y+1|z+1"
GROUP1_NUM = 1
GROUP1_X = 1
GROUP1_Y = 1
GROUP1_Z = 1

# INTERFACE = ["to_ddr", "to_chip"]

[group-level-3]
GROUP2_BANDWIDTH = 10 # GB/s
CONNECTION = "p2p"
GROUP2_NUM = 1