process_node = 7

[PCB.DRAM]
capacity = 83886080  # KB, 80G

[PCB.network]
bandwidth = 1024  # B/cycle 1555GB/s, A100
latency = 466

[PCB.compute_domain]
# size = [16, 1]
size = [8, 1]
# size = [4, 1]
# size = [2, 1]
# size = [1, 1]

[PCB.compute_domain.network]
topology = "mesh"
latency = 300
bandwidth = 8  # B/cycle A100 L2 ~7219.2GB/s

[PCB.compute_domain.package]
# size = [1, 1]
size = [2, 1]
# size = [4, 1]
# size = [8, 1]
# size = [16, 1]

[PCB.compute_domain.package.network]
topology = "mesh"
latency = 150
bandwidth = 16  # B/cycle A100 L2 ~7219.2GB/s

[PCB.compute_domain.package.chiplet]
size = [1, 8]

[PCB.compute_domain.package.chiplet.network]
topology = "mesh"
latency = 1
bandwidth = 32  # B/cycle A100 L2 ~7219.2GB/s

[PCB.compute_domain.package.chiplet.core.network]
bandwidth = "inf"  # B/cycle
latency = 1

[PCB.compute_domain.package.chiplet.core.mac_array]  # for mixed-precision, [[mac_array]] for multiple units
[PCB.compute_domain.package.chiplet.core.mac_array.fp16]
parallelism = [32, 32]
latency = 64

[PCB.compute_domain.package.chiplet.core.vector_unit]
[PCB.compute_domain.package.chiplet.core.vector_unit.fp16]
parallelism = 128
[PCB.compute_domain.package.chiplet.core.vector_unit.fp16.latency]
relu = 1  # latency for different operations
softmax = 9
add = 1

[PCB.compute_domain.package.chiplet.core.local_memory]
capacity = 2560  # KB, 512
latency = 1
bandwidth = 64
