process_node = 7

size = [2, 2]

[network]
topology = "mesh"
bandwidth = 1024
latency = 0

[chiplet]
size = [16, 8]

[chiplet.network]
topology = "mesh"
bandwidth = 16
latency = 0

[chiplet.core.network]
sram_bandwidth = 256
dram_bandwidth = 128
flash_bandwidth = 136

[chiplet.core.mac_array]  # for mixed-precision, [[mac_array]] for multiple units
[chiplet.core.mac_array.int8]
parallelism = [32, 32]
latency = 64

[chiplet.core.vector_unit]
[chiplet.core.vector_unit.int8]
parallelism = 128
[chiplet.core.vector_unit.int8.latency]
relu = 1  # latency for different operations
softmax = 9
add = 1

[chiplet.core.local_memory]
capacity = 2560  # KB, 512
latency = 0
bandwidth = 0

[chiplet.core.dram]
capacity = 2560  # KB, 512

[chiplet.core.flash]
capacity = 2560  # KB, 512