[PCB.DRAM]
capacity = 83886080  # KB, 80G

[PCB.network]
bandwidth = 1  # KB/cycle 1555GB/s, A100

[PCB.chiplet]
size = [16, 8]

[PCB.chiplet.network]
topology = "star"
bandwidth = 5661  # GB/s, A100 L2 2007.2 B/cycle

[PCB.chiplet.shared_memory]
capacity = 40960  # KB

[PCB.chiplet.core.network]
buffer2array_input = 151  # GB/s
buffer2array_weight = 151
array2buffer = 151
array2vector = 151
buffer2vector_input = 151
buffer2vector_params = 151
vector2buffer = 151
buffer2router = 151
router2buffer = 151

[PCB.chiplet.core.mac_array]  # for mixed-precision, [[mac_array]] for multiple units
fp16 = [32, 32]
fp32 = [16, 32]

[PCB.chiplet.core.vector_unit]
ReLU = 128
BN = 128
SoftMax = 128

[PCB.chiplet.core.local_memory]
capacity = 192  # KB
